# Generated by Django 5.1.1 on 2024-10-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_customer_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.IntegerField(
                choices=[
                    (2, "PROCESSED"),
                    (3, "DELIVERED"),
                    (4, "REJECTED"),
                    (1, "CONFIRMED"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="orededitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
