# Generated by Django 5.1.1 on 2024-11-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_order_total_price_alter_order_order_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_name", models.CharField(max_length=250)),
                ("card_number", models.CharField(max_length=100)),
                ("card_type", models.CharField(max_length=100)),
                ("cvv_number", models.CharField(max_length=100)),
            ],
        ),
    ]
